namespace AbhiTimesheet.Api.Contracts.Projects;

public sealed record ProjectRequest(
    string Name,
    string Code,
    string Description,
    string ClientBusinessUnit,
    string Department,
    string AdminId,
    string AdminName,
    string ManagerId,
    string ManagerName,
    string ProjectLead,
    string DeliveryModel,
    IReadOnlyList<string> TeamMemberIds,
    IReadOnlyList<string> TeamMemberNames,
    int TeamSize,
    decimal Budget,
    string Priority,
    string Status,
    string StartDate,
    string EndDate,
    bool IsBillable);

public sealed record ProjectDto(
    string Id,
    string Name,
    string Code,
    string Description,
    string ClientBusinessUnit,
    string Department,
    string AdminId,
    string AdminName,
    string ManagerId,
    string ManagerName,
    string ProjectLead,
    string DeliveryModel,
    IReadOnlyList<string> TeamMemberIds,
    IReadOnlyList<string> TeamMemberNames,
    int TeamSize,
    decimal Budget,
    string Priority,
    string Status,
    string StartDate,
    string EndDate,
    bool IsBillable,
    string CreatedAtUtc);
